### ISSUE TITLE
error when processing must-gather when finding invalid token: `<unicode string>` 

### ISSUE THREAD

**Issue by mtulio** [elmiko/okd-camgi#2]
Hi, nice report tool! My first time using. =)

## Problem 

I got this error when running from a random MG:

~~~bash
$ okd-camgi --webbrowser $MUST_GATHER_PATH
[...]
DEBUG:root:loading core/nodes yaml from ${MUST_GATHER_PATH}/cluster-scoped-resources/core/nodes/ocp-infra-hm.yaml
Traceback (most recent call last):
  File "/home/myuser/.local/bin/okd-camgi", line 11, in <module>
    sys.exit(main())
  File "/home/myuser/.local/lib/python3.6/site-packages/okd_camgi/main.py", line 45, in main
    content = load_index_from_path(args.path)
  File "/home/myuser/.local/lib/python3.6/site-packages/okd_camgi/main.py", line 27, in load_index_from_path
    index_context = IndexContext(mustgather)
  File "/home/myuser/.local/lib/python3.6/site-packages/okd_camgi/contexts.py", line 110, in __init__
    nodes = NodesContext([NodeContext(node) for node in mustgather.nodes])
  File "/home/myuser/.local/lib/python3.6/site-packages/okd_camgi/interfaces.py", line 67, in nodes
    nodes = self.resources('nodes', 'core')
  File "/home/myuser/.local/lib/python3.6/site-packages/okd_camgi/interfaces.py", line 133, in resources
    resource = self.resource_or_none(f[:-5], kind, group, namespace)
  File "/home/myuser/.local/lib/python3.6/site-packages/okd_camgi/interfaces.py", line 122, in resource_or_none
    resource = yaml.load(man_file.read(), Loader=yaml.FullLoader)
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/home/myuser/.local/lib/python3.6/site-packages/yaml/scanner.py", line 292, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 466, column 1:
    4ef
    ^
could not find expected ':'
  in "<unicode string>", line 467, column 1:
    
    ^
~~~
 I don't know why this char is inside the YAML collected by must-gather:

~~~bash
$ tail -n1 ${MUST_GATHER_PATH}/cluster-scoped-resources/core/nodes/ocp-infra-hm.yaml
4ef
~~~

## Resolution

I just removed it and run again and everything works.

## Next steps:

Some exception handling could check some kind of stuffs to prevent stop processing.

**Comment by elmiko** [comment]
hi! thanks for the report @mtulio =)

i've hit this problem with poorly formed yaml myself, i wasn't quite sure the best way to handle it. what if i add some exception handling and just print the name of the bad file with a warning about the line number or something?

**Comment by mtulio** [comment]
Hi @elmiko  it could be a good idea! So we will not stop the execution and the bad line will reported - and could be addressed for some source [must-gather collector script] that generated it.

**Comment by elmiko** [comment]
good idea, i will try to hack something up.
